# air.toml
root = "."  # project root
tmp_dir = "tmp"
build_cmd = "go build -o ./tmp/main"
log = "air.log"
run_cmd = ["./tmp/main"]
[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air 
silent = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true